### ISSUE TITLE
Cant log in with Github

### ISSUE THREAD

**Issue by nukeop** [adoptoposs/adoptoposs#129]
## Expected Behavior
I should be able to log in.

## Actual Behavior
Trying to log in redirects me to Github, where I authorize the application. The next page (still on Github) says it's about to redirect me, but it keeps loading. If I click on the manual redirect link, I am redirected to Adoptoposs, but it says "Authentication failed.", and I'm still not logged in.

## Steps to Reproduce the Problem
Described above.

## Specifications

  - Version: N/A
  - Platform: Firefox (latest) and Brave (latest)
  - Subsystem: N/A

Let me know if there's anything else I can do to help debug this.

**Comment by paulgoetze** [comment]
Thanks, @nukeop, for reporting. I suppose you were trying to login from desktop browsers?

I tried in Firefox v100.0 on Desktop and Mobile (Android) in normal and private mode and it worked fine for me :thinking: 

Did you already try to revoke the access for the Adoptoposs application from the "Authorized Oauth Apps" in you GitHub settings (https://github.com/settings/applications --> right tab) and then tried to log in again? I was thinking, maybe some token auth scopes were not granted before ( - whereas we have the minimum required read-only auth scopes, and they did not change for a long time).

Please let me know if it's still an issues, then I'll dig deeper.

**Comment by nukeop** [comment]
Hm, that didn't fix it - and I've tried another computer, 2 other browsers (Vivaldi, Chromium), and a different Github account. Is there any other way to log in?

**Comment by paulgoetze** [comment]
:( nevertheless, thanks for trying. Unfortunately there is not other way to log in right now. 
But the good news is: I was able to reproduce the issue and am going to work on a fix tomorrow.

**Comment by paulgoetze** [comment]
The fix went faster than expected - it's already deployed :rocket: 

The culprit was a blank (real) name from the GitHub account side, that needed to be handled during login. I had a name set in my GitHub account, that's why it worked for me. :upside_down_face: 

Could you please try to [log in](https://adoptoposs.org/auth/github) again and see if it works for you now?

**Comment by nukeop** [comment]
Thanks! I confirm it's working.
