### ISSUE TITLE
Possible to reduce GitHub permissions?

### ISSUE THREAD

**Issue by fhunleth** [adoptoposs/adoptoposs#40]
I think Adoptoposs is a super idea and the website looks great!

Would it be possible to reduce the necessary GitHub permissions, though? Here's what I'm seeing:

![Screenshot_2020-04-01_19-00-06](https://user-images.githubusercontent.com/64669/78194507-63906c80-744b-11ea-95b5-9300e634b717.png)

Read access to public repositories is obviously fine. Write access is a little scary, and I wasn't sure why it was needed. The same goes to write access to personal user data. I'm also slightly concerned about read-access to private project boards, but I haven't dug into see if that exposes any proprietary information from corporate GitHub orgs that I'm in.

**Comment by paulgoetze** [comment]
Hey, @fhunleth. Thanks for reporting, I think you are absolutely right.
I just had another look into the [GitHub API scopes](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes) and as far as I could see in a quick test, following scopes should be sufficient:

`read:user user:email read:org`

(currently we have `user public_repo read:org` – https://github.com/adoptoposs/adoptoposs/blob/staging/config/config.exs#L42)

I’ll double check later today if all features still work as expected, and change it to the more restricted ones.

**Comment by paulgoetze** [comment]
@fhunleth :rocket: more restricted permission are deployed. You should be able to log in under read-only permission after revoking access for the Adoptoposs OAuth app in your GitHub Applications settings.

**Comment by fhunleth** [comment]
I tried again. I actually didn't have a login so I didn't have to revoke access. The new permissions look much better. However, "Adoptoposs says sorry!" I hope that you received an error report, since I don't think that I have anything additional to add. I just told GitHub to grant access and I got redirected to the 500 error screen.

**Comment by paulgoetze** [comment]
I see some database connection errors for about that time of your comment. From what I can see it looks like these are not related to the last deployment and it was an unfortunate coincidence to appear shortly after. Anyway, thanks for letting me know. :+1:
