### ISSUE TITLE
Long project names mess up layout on mobile screens

### ISSUE THREAD

**Issue by paulgoetze** [adoptoposs/adoptoposs#71]
## Expected Behavior
Project cards for projects with long names have a maximum size of the screen width.

## Actual Behavior
Long project names mess up the layout for mobile screen size, because there’s no auto line breaks or some other overflow handling in place to keep the size of the project card at max of the screen width. So the project card extends beyong the page background, and allows for the whole page scroll horizontally.

## Steps to Reproduce the Problem

  1. Login and submit a project with a very long name
  1. Search for it on a mobile screen size

Needs some CSS knowledge. I figure it makes sense to still see the full project name (no ellipsis or the like)?

**Comment by co0lsky** [comment]
I'm not sure why I can't assign myself to this issue, but I'll pick up this issue this week
