### ISSUE TITLE
Add CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by paulgoetze** [adoptoposs/adoptoposs#74]
…with a list all contributors of the project, for motivation and showing appreciation. 

* Add a sentence or two to the CONTRIBUTING.md to encourage contributors to add their name & GitHub handle link to the list when doing their first contribution.
* Link to CONTRIBUTORS.md from README.md
* Add already available contributors  (most recent  on top) to the list when creating the file.

**Comment by Cheemashyper** [comment]
Hello @paulgoetze ,
I would like to work on this issue and add the Contributions.md files with all the requirements you said.
I will be waiting for you to assign me this issue and I will start working right away!

**Comment by JPYamamoto** [comment]
I'm really sorry @Cheemashyper , I just noticed that you asked for this issue, and I already sent a pull-request. I'll let @paulgoetze decide what to do. I get it if my pull-request gets declined for this reason. My apologies.

**Comment by paulgoetze** [comment]
Thanks for your interest in taking this on, @Cheemashyper, and your pull-request @JPYamamoto. :purple_heart: 
I'm going to merge the PR, once it passed review. But I think asking for being assigned to work on an issue is the better workflow, also to avoid that multiple people unnecessarily spend their time on the same thing.

It was not stated anywhere, so nobodies fault here. We can add it to the Contributions guide. So, good that we ran into that case now ;).
